[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:api]
command=uvicorn api:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
environment=SCALEDOWN_API_KEY="%(ENV_SCALEDOWN_API_KEY)s",TAVILY_API_KEY="%(ENV_TAVILY_API_KEY)s",NEWSDATA_API_KEY="%(ENV_NEWSDATA_API_KEY)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:streamlit]
command=streamlit run app.py --server.port 7860 --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
directory=/app
autostart=true
autorestart=true
environment=API_URL="http://127.0.0.1:8000",SCALEDOWN_API_KEY="%(ENV_SCALEDOWN_API_KEY)s",TAVILY_API_KEY="%(ENV_TAVILY_API_KEY)s",NEWSDATA_API_KEY="%(ENV_NEWSDATA_API_KEY)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
